- hosts: all
  tasks:
    - import_tasks: tasks/main.yml
  handlers:
    - import_tasks: handlers/main.yml
  vars_files:
    - 'defaults/main.yml'

#- hosts: postfix-fallback
#  tasks:
#    - import_tasks: tasks/main.yml
#  handlers:
#    - import_tasks: handlers/main.yml
#  vars_files:
#    - 'defaults/fallback.yml'
